export const AccessState = [
  {
    results: [
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
    ],
  },
];
