const ShowAllTestSeriesSection = [
  {
    mainHeading: 'Class 11 IIT JEE Batches',
    url: '/test-series/iit-jee/Class-11',
    results: [
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
    ],
  },
  {
    mainHeading: 'Class 12 IIT JEE Batches',
    url: '/test-series/iit-jee/Class-12',
    results: [
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
    ],
  },
  {
    mainHeading: 'Dropper IIT JEE Batches',
    url: '/test-series/iit-jee/Dropper',
    results: [
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
      {
        title: 'Lakshaya JEE Mains & Advanced 2023',
        banner: '/batch-card-banner.webp',
        usedFor: 'JEE Mains & Advanced 2023',
        features: ['Live Lecture', 'Offline Tests', 'DPPs & more'],
        startDate: 'One to One telephonic PTM, based on SPD',
        endDate: "Seminars/ Topper's talk at Offline center",
        originalCost: '1999',
        updatedCost: '11000',
        language: 'Hinglish',
        content: 'online',
      },
    ],
  },
];
export default ShowAllTestSeriesSection;
