export enum WidgetEnum {
  CAROUSEL = 'CAROUSEL',
  HERO_SECTION = 'HERO_SECTION',
  EXAM_CATEGORIES = 'EXAM_CATEGORIES',
  VIDYAPEETH = 'VIDYAPEETH',
  FEATURE_LIST = 'FEATURE_LIST',
  STATS = 'STATS',
  RESULTS = 'RESULTS',
  APP_DOWNLOAD = 'APP_DOWNLOAD',
  TESTIMONIALS = 'TESTIMONIALS',
  STUDY_RESOURCE = 'STUDY_RESOURCE',
  YOUTUBE_STATS = 'YOUTUBE_STATS',
}
